# Generated by Django 2.1 on 2018-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assid', models.AutoField(db_column='AssId', primary_key=True, serialize=False)),
                ('archived', models.IntegerField(db_column='Archived')),
            ],
            options={
                'db_table': 'Assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OAuth',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phone_no', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'o_auth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('tasksnumber', models.IntegerField(db_column='TasksNumber')),
                ('startdate', models.DateField(db_column='StartDate')),
                ('enddate', models.DateField(db_column='EndDate')),
                ('duration', models.SmallIntegerField(db_column='Duration')),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('location', models.CharField(db_column='Location', max_length=200)),
                ('status', models.FloatField(db_column='Status')),
                ('archived', models.IntegerField(db_column='Archived')),
                ('projectid', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('reportid', models.AutoField(db_column='ReportId', primary_key=True, serialize=False)),
                ('comments', models.TextField(db_column='Comments')),
                ('author', models.CharField(db_column='Author', max_length=80)),
                ('time', models.DateTimeField(db_column='Time')),
                ('taskid', models.IntegerField(db_column='TaskId')),
                ('projectid', models.IntegerField(db_column='ProjectId')),
            ],
            options={
                'db_table': 'Reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('grouping', models.CharField(db_column='Grouping', max_length=200)),
                ('originalquantity', models.IntegerField(db_column='OriginalQuantity')),
                ('resourceid', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskid', models.AutoField(db_column='TaskId', primary_key=True, serialize=False)),
                ('progress', models.FloatField(blank=True, db_column='Progress', null=True)),
                ('archived', models.IntegerField(db_column='Archived')),
                ('earlystart', models.FloatField(db_column='earlyStart')),
                ('earlyfinish', models.FloatField(db_column='earlyFinish')),
                ('latestart', models.FloatField(db_column='lateStart')),
                ('latefinish', models.FloatField(db_column='lateFinish')),
                ('duration', models.FloatField(db_column='Duration')),
                ('preceedingtasks', models.TextField(db_column='PreceedingTasks')),
            ],
            options={
                'db_table': 'Tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebAuth',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=300)),
                ('type', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'web_auth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workerids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=40)),
                ('workhours', models.FloatField(db_column='Workhours')),
            ],
            options={
                'db_table': 'WorkerIds',
                'managed': False,
            },
        ),
    ]
